#!/bin/bash

# APS业务模块双模式改造检查清单
# 使用方法：./改造检查清单.sh <模块名称>

MODULE_NAME=${1:-"示例模块"}

echo "=========================================="
echo "APS业务模块双模式改造检查清单"
echo "模块名称: $MODULE_NAME"
echo "=========================================="
echo ""

# 后端部分
echo "📦 后端部分"
echo "----------------------------------------"
echo "□ 确认使用正确的数据库表"
echo "□ 检查数据库表结构是否完整"
echo "□ 添加缺失的数据库字段"
echo "□ 更新Model文件定义"
echo "□ Controller层添加CRUD方法"
echo "□ Service层实现业务逻辑"
echo "□ 数据格式化方法（formatXxx）"
echo "□ 软删除实现"
echo "□ 自动编号生成"
echo "□ 路由配置"
echo "□ 日志记录"
echo "□ 错误处理"
echo ""

# 前端部分
echo "🌐 前端部分"
echo "----------------------------------------"
echo "□ 确认使用正确的API版本（V1/V2）"
echo "□ 检查API路径前缀（/api/ 或 /api/v2/）"
echo "□ 模拟数据API实现"
echo "□ 真实API客户端实现"
echo "□ 统一API服务配置"
echo "□ API基础URL配置"
echo "□ 环境变量配置"
echo "□ 响应格式兼容处理"
echo "□ 检查所有Store文件导入（api-unified）"
echo "□ 前端UI更新（新增、删除按钮）"
echo "□ 对话框支持新增和编辑"
echo "□ 新增表单自动生成主键"
echo "□ 业务逻辑实现"
echo "□ 字段名映射处理"
echo "□ 数组与字符串转换"
echo "□ 用户确认对话框"
echo "□ 错误处理和提示"
echo ""

# 测试部分
echo "🧪 测试部分"
echo "----------------------------------------"
echo "□ 真实API模式测试"
echo "  □ 查询功能"
echo "  □ 新增功能"
echo "  □ 编辑功能"
echo "  □ 删除功能"
echo "□ 模拟数据模式测试"
echo "  □ 查询功能"
echo "  □ 新增功能"
echo "  □ 编辑功能"
echo "  □ 删除功能"
echo "□ 模式切换测试"
echo "□ 数据格式验证"
echo "□ 边界情况测试"
echo ""

# 常见问题检查
echo "⚠️  常见问题检查"
echo "----------------------------------------"
echo "□ API路径配置正确"
echo "□ 端口配置一致（前后端）"
echo "□ 数据格式统一"
echo "□ 字段映射正确"
echo "□ 数组/字符串转换"
echo "□ 软删除实现"
echo "□ 错误处理完善"
echo ""

echo "=========================================="
echo "改造完成后请运行以下命令测试："
echo "=========================================="
echo ""
echo "# 1. 检查服务状态"
echo "/Users/yoki/IDEProjects/JN-APS/check-services.sh"
echo ""
echo "# 2. 测试真实API"
echo "curl http://localhost:3002/api/<模块路径>/items"
echo ""
echo "# 3. 测试前端访问"
echo "open http://localhost:5173/"
echo ""
echo "# 4. 查看详细文档"
echo "cat /Users/yoki/IDEProjects/JN-APS/APS改造最佳实践.md"
echo ""
echo "=========================================="
